### PR TITLE
Fix circleci pipeline

### PR DESCRIPTION
**Pull request by LuRsT**
I added the initial CircleCI pipeline in `master`. It isn't working as of now.

This PR aims to fix the pipeline and test how it works on PRs.

### CODE REVIEW

**Comment by andrewdevile** [comment]
After spending some time reading about poetry and the guidelines, this made sense. But I think this PR could benefit from a bit more context/better description.

**Comment by LuRsT** [comment]
Thanks for the comment @andrewdevile, I have updated the PR description

**Comment by pssuils** [comment]
@LuRsT I think I personally benefit from knowing more about poetry/lock files, I'm guessing a guideline somewhere is coming?

**Comment by LuRsT** [comment]
It's already here @pssuils https://github.com/unmadeworks/way-we-work/commit/5538e83209db2365816cc0f9c55a845fa8bc2d0e

**Pull request merged**
